# Generated by Django 2.2 on 2019-06-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('userStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemType', models.IntegerField()),
                ('itemAttribute1', models.IntegerField()),
                ('itemAttribute2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceName', models.CharField(max_length=100)),
                ('racePhoto', models.CharField(max_length=100)),
                ('raceHp', models.IntegerField()),
                ('raceAtk', models.IntegerField()),
                ('raceDef', models.IntegerField()),
                ('raceSpa', models.IntegerField()),
                ('raceSpd', models.IntegerField()),
                ('raceSpe', models.IntegerField()),
                ('raceability', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillType', models.CharField(max_length=100)),
                ('skillPhoto', models.CharField(max_length=100)),
                ('skillPower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100)),
                ('teamItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('teamOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GameUser')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='memberRace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Race'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
