# Generated by Django 2.2.1 on 2019-06-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='raceType',
            field=models.CharField(default='电', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='skillClass',
            field=models.CharField(default='物理', max_length=100),
        ),
    ]
