# Generated by Django 2.2 on 2019-05-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pw', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prepare.GameUser')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberclass', models.CharField(max_length=10)),
                ('ability1', models.CharField(max_length=10)),
                ('ability2', models.CharField(max_length=10)),
                ('ability3', models.CharField(max_length=10)),
                ('skill1', models.CharField(max_length=10)),
                ('skill2', models.CharField(max_length=10)),
                ('skill3', models.CharField(max_length=10)),
                ('skill4', models.CharField(max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prepare.Team')),
            ],
        ),
    ]
